((:type           . "rest")
(:version         . "1")
(:name            . "Cluster-DR")
(:protocol        . "http")
(:host            . "DR1.OpsResearch.com")
(:port            . 8000)
(:eval-path       . "/LATEST/eval")
(:documents-path  . "/LATEST/documents")
(:rest-apis-path  . "/LATEST/rest-apis")
(:user            . "admin")
(:password        . "passw0rd"))